spring.application.name=Hospital-Management-System
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDb
spring.datasource.username=postgres
spring.datasource.password=Smit45@#
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

jwt.secretKey=SECRETKEY


